data_format:
  separator: ","
  header: true
  date_column: "dteday"
column_mapping: {}
profile_sections:
  - "data_drift"
pretty_print: true
sampling:
  reference:
    type: "simple" # could be "none", "simple", "random"
    skip_rows: 5 # used with simple sampling, number of rows to skip
    ratio: 0.1   # used with random sampling, part of data to take from chunk
  production:
    type: "simple" # could be "none", "simple", "random"
    skip_rows: 5 # used with simple sampling, number of rows to skip
    ratio: 0.1   # used with random sampling, part of data to take from chunk